# Generated by Django 4.1.2 on 2022-12-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название машины')),
                ('color', models.CharField(max_length=128, verbose_name='Цвет автомобиля')),
                ('description', models.TextField(verbose_name='Описание машины')),
                ('type', models.IntegerField(choices=[(1, 'Sedan'), (2, 'Truck'), (4, 'SUV')], verbose_name='Тип кузова автомобиля')),
            ],
        ),
    ]
