# Generated by Django 4.1.2 on 2022-10-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Кличка кота')),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год рождения кота')),
            ],
        ),
    ]
