# Generated by Django 4.1.2 on 2022-10-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='color',
            field=models.CharField(choices=[('BLACK', 'Black'), ('WHITE', 'White'), ('ORANGE', 'Orange')], default='BLACK', max_length=20, verbose_name='Цвет шерсти'),
            preserve_default=False,
        ),
    ]
