# Generated by Django 4.1.2 on 2022-10-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_person_cat_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='cats.person', verbose_name='Хозяин кота'),
            preserve_default=False,
        ),
    ]
