# Generated by Django 4.1.2 on 2022-10-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='achievements',
            field=models.ManyToManyField(to='cats.achievement', verbose_name='Действия, совершенные котом'),
        ),
    ]
